inici:
    pattern:  /
    defaults: { _controller: BlogBundle:Default:inici }

presentacio:
    pattern:  /presentacio/
    defaults: { _controller: BlogBundle:Default:presentacio }

projectes:
    pattern:  /projectes/
    defaults: { _controller: BlogBundle:Default:projectes }
     
publicacions:
    pattern:  /publicacions/
    defaults: { _controller: BlogBundle:Default:publicacions }

jornada:
    pattern:  /jornades/{titol}
    defaults: { _controller: BlogBundle:Default:jornada }
    
jornades:
    pattern:  /jornades/
    defaults: { _controller: BlogBundle:Default:llistaJornades }
    
jornada:
    pattern:  /jornades/{titol}
    defaults: { _controller: BlogBundle:Default:jornada }
    
arxiu:
    pattern:  /arxiu/
    defaults: { _controller: BlogBundle:Default:arxiu }

contacte:
    pattern:  /contacte/
    defaults: { _controller: BlogBundle:Default:contacte }
    
enllasos:
    pattern:  /enlla√ßos/
    defaults: { _controller: BlogBundle:Default:enllasos }